/* eslint-disable jsx-a11y/alt-text -- @react-pdf/renderer Image is not an HTML <img>; it has no alt attribute. */
import { Document, Image, Page, Text, View } from "@react-pdf/renderer";

import { formatCents } from "@/lib/money";
import type { ReportPacket } from "@/lib/queries/report";
import { itemAggregateCents, type ReportItem } from "@/lib/report";
import type { PdfImage } from "./images";
import { paginateRooms } from "./paginate";
import { COLORS, styles } from "./styles";

type ImageMap = Map<number, PdfImage[]>;

function fmtDate(iso: string | null): string {
  if (!iso) return "—";
  const d = new Date(iso);
  if (Number.isNaN(d.getTime())) return "—";
  return new Intl.DateTimeFormat("en-US", {
    year: "numeric",
    month: "short",
    day: "numeric",
  }).format(d);
}

const STATUS = {
  within: { color: COLORS.within, label: "Within coverage" },
  approaching: { color: COLORS.approaching, label: "Approaching limit" },
  over: { color: COLORS.over, label: "Over limit" },
} as const;

function RunningHeader({ name }: { name: string }) {
  return (
    <View style={styles.runningHeader} fixed>
      <Text>{name} — Home Inventory</Text>
      <Text>Proof-of-loss packet</Text>
    </View>
  );
}

function Footer() {
  return (
    <View style={styles.footer} fixed>
      <Text>
        Generated by DomicileDB · Informational only — verify with your insurer.
      </Text>
      <Text
        render={({ pageNumber, totalPages }) => `${pageNumber} / ${totalPages}`}
      />
    </View>
  );
}

function Spec({ label, value }: { label: string; value: string | null }) {
  if (!value) return null;
  return (
    <View style={styles.spec}>
      <Text style={styles.specLabel}>{label}</Text>
      <Text>{value}</Text>
    </View>
  );
}

function ItemBlock({ item, images }: { item: ReportItem; images: PdfImage[] }) {
  const agg = itemAggregateCents(item);
  const perItem =
    item.replacementCostCents !== null
      ? formatCents(item.replacementCostCents)
      : "—";
  return (
    <View style={styles.item} wrap={false}>
      <View style={styles.itemTitleRow}>
        <Text style={styles.itemTitle}>{item.title}</Text>
        <Text style={styles.bold}>
          {agg !== null ? formatCents(agg) : "No value"}
        </Text>
      </View>

      <View style={styles.specGrid}>
        <Spec label="Category" value={item.categoryName} />
        <Spec label="Manufacturer" value={item.manufacturer} />
        <Spec label="Model" value={item.modelNumber} />
        <Spec label="Serial" value={item.serialNumber} />
        <Spec
          label="Quantity"
          value={item.quantity > 1 ? String(item.quantity) : null}
        />
        <Spec label="Condition" value={item.condition} />
        <Spec label="Age" value={item.ageEstimate} />
        <Spec
          label="Replacement (each)"
          value={item.quantity > 1 && agg !== null ? perItem : null}
        />
        <Spec
          label="Price paid"
          value={
            item.pricePaidCents !== null
              ? `${formatCents(item.pricePaidCents)} (${fmtDate(item.purchaseDate)})`
              : null
          }
        />
      </View>

      {images.length > 0 ? (
        <View style={styles.photoRow}>
          {images.map((img, i) => (
            <Image key={i} src={img} style={styles.photo} />
          ))}
        </View>
      ) : null}

      {item.documents.length > 0 ? (
        <Text style={[styles.faint, { marginTop: 4 }]}>
          Attached: {item.documents.map((d) => d.kind).join(", ")}
        </Text>
      ) : null}
    </View>
  );
}

function CoverageLine({ coverage }: { coverage: ReportPacket["coverage"] }) {
  if (
    !coverage.hasPolicy ||
    coverage.limitCents === null ||
    coverage.status === null
  ) {
    return (
      <Text style={[styles.muted, { marginTop: 6 }]}>
        No Coverage B limit on file.
      </Text>
    );
  }
  const s = STATUS[coverage.status];
  const pct = Math.round((coverage.pctUsed ?? 0) * 100);
  return (
    <View style={[styles.row, { marginTop: 8, alignItems: "center" }]}>
      <Text style={styles.muted}>
        Coverage B limit {formatCents(coverage.limitCents)}
      </Text>
      <Text style={[styles.pill, { color: "#fff", backgroundColor: s.color }]}>
        {s.label} · {pct}%
      </Text>
    </View>
  );
}

export function ProofPacketDocument({
  packet,
  imagesByItem,
}: {
  packet: ReportPacket;
  imagesByItem: ImageMap;
}) {
  const chunks = paginateRooms(packet.rooms);
  return (
    <Document
      title={`${packet.householdName} — Home Inventory`}
      author="DomicileDB"
    >
      <Page size="LETTER" style={styles.page}>
        <RunningHeader name={packet.householdName} />

        <Text style={styles.h1}>Home Inventory</Text>
        <Text style={styles.muted}>Claim-ready proof-of-loss packet</Text>
        <Text style={{ marginTop: 8 }}>{packet.householdName}</Text>
        {packet.householdAddress ? (
          <Text style={styles.muted}>{packet.householdAddress}</Text>
        ) : null}
        <Text style={[styles.faint, { marginTop: 2 }]}>
          Generated {fmtDate(packet.generatedAt)} · {packet.filterLabel}
        </Text>

        <View style={styles.summaryBox}>
          <Text style={styles.faint}>
            Total replacement value (active, valued items)
          </Text>
          <Text style={styles.summaryTotal}>
            {formatCents(packet.grandTotalCents)}
          </Text>
          <Text style={styles.muted}>
            {packet.countedCount} valued · {packet.excludedCount} not yet valued
            · {packet.itemCount} active items
          </Text>
          <CoverageLine coverage={packet.coverage} />
        </View>

        {packet.categoryTotals.length > 0 ? (
          <View style={{ marginTop: 14 }}>
            <Text style={styles.h2}>Totals by category</Text>
            {packet.categoryTotals.map((c) => (
              <View key={c.name} style={styles.tableRow}>
                <Text>{c.name}</Text>
                <Text style={styles.bold}>{formatCents(c.cents)}</Text>
              </View>
            ))}
          </View>
        ) : null}

        <Text style={styles.disclaimer}>
          This document is an inventory record for insurance purposes. Values
          are owner-provided estimates of replacement cost and are informational
          only — they are not a determination of coverage. Verify all coverage
          and settlement terms with your insurer.
        </Text>
        <Footer />
      </Page>

      {chunks.length === 0 ? (
        <Page size="LETTER" style={styles.page}>
          <RunningHeader name={packet.householdName} />
          <Text style={styles.h2}>Inventory by location</Text>
          <Text style={styles.muted}>No active items to report.</Text>
          <Footer />
        </Page>
      ) : (
        chunks.map((chunk, idx) => (
          <Page key={idx} size="LETTER" style={styles.page}>
            <RunningHeader name={packet.householdName} />
            {idx === 0 ? (
              <Text style={styles.h2}>Inventory by location</Text>
            ) : null}
            <View style={styles.roomHeader}>
              <Text style={styles.roomTitle}>
                {chunk.room.locationName}
                {chunk.continued ? " (cont.)" : ""}
              </Text>
              <Text style={styles.bold}>
                {formatCents(chunk.room.totalCents)}
              </Text>
            </View>
            {chunk.items.map((it) => (
              <ItemBlock
                key={it.id}
                item={it}
                images={imagesByItem.get(it.id) ?? []}
              />
            ))}
            <Footer />
          </Page>
        ))
      )}
    </Document>
  );
}
