import { StyleSheet } from "@react-pdf/renderer";

export const COLORS = {
  ink: "#171717",
  muted: "#525252",
  faint: "#a3a3a3",
  line: "#e5e5e5",
  within: "#16a34a",
  approaching: "#d97706",
  over: "#dc2626",
};

export const styles = StyleSheet.create({
  page: {
    paddingTop: 54,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontSize: 9,
    color: COLORS.ink,
    fontFamily: "Helvetica",
    lineHeight: 1.4,
  },
  runningHeader: {
    position: "absolute",
    top: 24,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 8,
    color: COLORS.faint,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
    paddingBottom: 6,
  },
  footer: {
    position: "absolute",
    bottom: 22,
    left: 40,
    right: 40,
    flexDirection: "row",
    justifyContent: "space-between",
    fontSize: 7,
    color: COLORS.faint,
  },
  // Large fonts need an explicit lineHeight + margin or react-pdf under-sizes
  // the line box and the next line overlaps.
  h1: {
    fontSize: 20,
    fontFamily: "Helvetica-Bold",
    lineHeight: 1.2,
    marginBottom: 4,
  },
  h2: {
    fontSize: 13,
    fontFamily: "Helvetica-Bold",
    lineHeight: 1.2,
    marginBottom: 6,
  },
  roomHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "flex-end",
    marginTop: 14,
    marginBottom: 6,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.ink,
  },
  roomTitle: { fontSize: 13, fontFamily: "Helvetica-Bold" },
  muted: { color: COLORS.muted },
  faint: { color: COLORS.faint },
  bold: { fontFamily: "Helvetica-Bold" },
  summaryBox: {
    borderWidth: 1,
    borderColor: COLORS.line,
    borderRadius: 4,
    padding: 12,
    marginTop: 14,
  },
  summaryTotal: {
    fontSize: 22,
    fontFamily: "Helvetica-Bold",
    lineHeight: 1.15,
    marginTop: 2,
    marginBottom: 4,
  },
  row: { flexDirection: "row", justifyContent: "space-between" },
  tableRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    paddingVertical: 3,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  item: {
    marginBottom: 10,
    paddingBottom: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.line,
  },
  itemTitleRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginBottom: 2,
  },
  itemTitle: { fontSize: 11, fontFamily: "Helvetica-Bold" },
  specGrid: { flexDirection: "row", flexWrap: "wrap", marginTop: 2 },
  spec: { width: "33%", marginBottom: 2 },
  specLabel: { fontSize: 7, color: COLORS.faint, textTransform: "uppercase" },
  photoRow: { flexDirection: "row", marginTop: 6, gap: 4 },
  photo: { width: 70, height: 70, objectFit: "cover", borderRadius: 2 },
  // Wider room/area shots: larger than item thumbnails to convey context.
  roomPhoto: { width: 120, height: 90, objectFit: "cover", borderRadius: 2 },
  pill: {
    fontSize: 8,
    paddingVertical: 2,
    paddingHorizontal: 6,
    borderRadius: 8,
    fontFamily: "Helvetica-Bold",
  },
  disclaimer: {
    marginTop: 12,
    fontSize: 8,
    color: COLORS.muted,
    fontStyle: "italic",
  },
});
